lib/backend/postgres/index.ts
lib/cards/authentication.ts
lib/cards/index.ts
lib/cards/user-settings.ts
lib/kernel.ts
test/integration/backend/index.spec.ts
test/integration/kernel.spec.ts

This is the first step in preparation for a refactor on how JF handles permissions. These two new types are automatically updated when `user` contracts are updated.
JIP: https://jel.ly.fish/improvement-jip-remove-field-level-permissions-8d561c94-2d33-4026-829c-272600018558

Add the `user-settings` and `authentication` types

---

lib/backend/postgres/cards.spec.ts
lib/backend/postgres/cards.ts
lib/backend/postgres/index.ts
lib/backend/postgres/jsonschema2sql/index.spec.ts
lib/backend/postgres/jsonschema2sql/index.ts
lib/backend/postgres/jsonschema2sql/sql-query.ts
lib/backend/postgres/links.ts
lib/backend/postgres/streams.ts
lib/context.ts
lib/kernel.ts
lib/permission-filter.ts
test/integration/backend/helpers.ts
test/integration/backend/postgres/index.spec.ts
test/integration/backend/postgres/jsonschema2sql/index.spec.ts
test/integration/backend/postgres/streams/index.spec.ts

Currently, many functions take an argument called `context`. This is simply an arbitrary object that should be passed as first argument to calls into the logging or assert libraries. This commit introduces a `Context` class that encapsulates the logging context. It also exposes logging and assert functions so that, for example, calls like `logger.info(context, ...` are replaced by `context.info(...`.
In the future the `Context` class will carry more than just the log context.

Rationalize the use of a "context"

---

lib/backend/postgres/cards.ts
lib/backend/postgres/index.ts
lib/backend/postgres/jsonschema2sql/errors.ts
lib/backend/postgres/jsonschema2sql/table-index.ts
lib/errors.ts
test/integration/backend/index.spec.ts
test/integration/kernel.spec.ts

Connects-to: https://github.com/product-os/jellyfish-types/issues/336

Restrict usage of `jellyfish-types` to only `JSONSchema` and the contract types

---

lib/backend/index.ts
lib/backend/postgres/index.ts
lib/index.ts

- Put proper types in the exported `create` function instead of `any`s.
- Properly export the `Cache` type.
- Export `PostgresBackendOptions`.
- Temporarely make `CoreBackend.connection` public because the queue requires access to it.

More interface fixes

---

lib/backend/index.ts
lib/backend/postgres/cards.ts
lib/backend/postgres/index.ts
lib/backend/postgres/jsonschema2sql/index.spec.ts
lib/backend/postgres/jsonschema2sql/index.ts
lib/backend/postgres/jsonschema2sql/sql-query.ts
lib/backend/postgres/streams.ts
lib/index.ts
lib/json-schema.ts
lib/kernel.ts
lib/permission-filter.ts
lib/views.ts
package.json
test/integration/backend/helpers.ts
test/integration/backend/index.spec.ts
test/integration/backend/postgres/jsonschema2sql/index.spec.ts
test/integration/cache/index.spec.ts
test/integration/helpers.ts
test/integration/kernel.disconnect.spec.ts
test/integration/kernel.spec.ts
test/integration/permission-filter.spec.ts
test/integration/views.spec.ts

- Remove the `core*` prefix from exported symbols.
- Do not export `PostgresBackend`. This is an implementation detail.
- Replace the `create` function with a static method in the `Kernel`: `withPostgres`.
- `Kernel.initialize` now takes a `LogContext` instead of a `MixedContext` as it doesn't make sense for it to accept a `Context` object.
- Update `jellyfish-types` to v2 and use the new `JsonSchema` type.

Update the API

---

lib/backend/postgres/index.ts

---
Currently, calling `reset()` results in the following Postgres errors:
```
postgres_1  | 2022-01-06 02:57:00.407 UTC [4866] ERROR:  cannot truncate a table referenced in a foreign key constraint
postgres_1  | 2022-01-06 02:57:00.407 UTC [4866] DETAIL:  Table "links2" references "cards".
postgres_1  | 2022-01-06 02:57:00.407 UTC [4866] HINT:  Truncate table "links2" at the same time, or use TRUNCATE ... CASCADE.
```

Fix Postgres reset statement

---

lib/kernel.ts
test/integration/views.spec.ts

The current signature defines that the method returns a partial contract while in fact it returns a full contract with only the ID undefined.
Unfortunately this is a major change as it is necessary to change the generic arguments.

Fix `Kernel.defaults` signature

---

lib/backend/postgres/index.ts
lib/backend/postgres/jsonschema2sql/index.ts
lib/backend/postgres/jsonschema2sql/sql-query.ts
lib/backend/postgres/streams.ts
lib/backend/postgres/types.ts
lib/index.ts
lib/kernel.ts
test/integration/backend/postgres/jsonschema2sql/index.spec.ts

Refactor `SqlQueryOptions`/`BackendQueryOptions` and export the refactored `QueryOptions` type

---

lib/backend/index.ts
lib/backend/postgres/index.ts
lib/backend/postgres/streams.ts
lib/index.ts

---
Add and export the `StreamChange` type. This type is currently used in `apps/server` in the main JF repo and is defined in `jellyfish-types`. This is another step in dropping `jellyfish-types`.
@Ereski Let me know if you think there is a better place to put this type.

Add and export StreamChange type

---

lib/authorization/markers.ts

---
Guess we have some missing marker tests...
Shows that we should test beta packages against consumers before merging anything even semi-serious like refactors.

Fix markers org query

---

lib/backend/postgres/streams.ts
lib/kernel.ts

---
Mask is not applied properly when calling `stream.emit('query', ...)`.

Apply mask to query with view

---

lib/authorization/index.ts
lib/authorization/utils.ts
lib/kernel.ts
lib/views.ts
test/integration/kernel.spec.ts
test/integration/views.spec.ts

This reverts commit 23eefb30244cc78cb1ffdc667519d2fe7166abd8.

Revert "Use `allOf` for merging schemas instead of `skhema.merge`"

---

lib/contracts/role-user-guest.ts

This changes the guest user role so that it can only view the guest user
contract. This change goes hand-in-hand with updates to the worker
service that add special routes for login and password reset.
See https://github.com/product-os/jellyfish/pull/7774
Signed-off-by: Lucian Buzzo lucian.buzzo@gmail.com

Restrict guest user role

---

lib/contracts/mixins/with-events.ts
lib/contracts/org.ts

`$events` is a shorthand for getting whisper and message contracts from
a timeline, and will be deprecated in future versions of Jellyscript.
The current implementation of `$events` uses a standalone AST parsing algorithm which
needs to be removed.

Mixins: Stop using `$events` in formulas

---

lib/contracts/mixins/with-events.ts
package.json
test/unit/mixins.spec.ts

Firstly, this PR fixes the incorrect link verb for traversing event contracts in the `.withEvent()` mixin.
Secondly, this PR adds a simple unit test to sanity check the formula used for aggregating values in the `withEvents()` mixin, alongside updates to jellyscript. 
This change highlights that the core should probably not be providing mixins, especially with functionality that it doesn't provide or handle directly ($$formula fields). 
In the future, we should consider hoisting mixins into the worker module to improve feature separation and make the system less brittle.

mixins: Add unit test for .withEvents()

---

lib/contracts/mixins/with-events.ts
package.json
test/unit/mixins.spec.ts

This change ensures that the initial value for tags is kept when aggregating tags.
Previously, if a tag was added directly, it would be overriden by the
AGGREGATE.

mixins: use initial value when aggregating tags

---

lib/backend/postgres/index.ts

Tentative fix for a memory leak in the database.

Recycle DB connections after 7500 uses by default

---

lib/backend/postgres/index.ts
lib/contracts/authentication-oauth.ts
lib/contracts/authentication-password.ts
lib/contracts/index.ts
lib/contracts/role-user-community.ts
lib/contracts/user-settings.ts
lib/kernel.ts

Two new types: `authentication-password` and `authentication-oauth`.

Split the `authentication` contract into two

---

lib/backend/postgres/index.ts

Fix the new `authentication-*` contracts being inserted as the old `authentication` type

---

README.md
lib/errors.ts
lib/kernel.ts
test/integration/kernel.link.spec.ts
test/integration/kernel.spec.ts

This is the PR for the [relationship contract" JIP](https://jel.ly.fish/improvement-jip-link-constraints-using-relationship-contract-f3666fd0-e5d6-4ca4-9fa8-73959e72e7c3)
It adds logic to the kernel to validate links on inserts and upserts: each link must be backed by a relationship contract.
Testing in:
- https://github.com/product-os/jellyfish-plugin-default/pull/1157
- https://github.com/product-os/jellyfish-plugin-product-os/pull/815
- https://github.com/product-os/jellyfish-plugin-github/pull/890
- https://github.com/product-os/jellyfish-plugin-channels/pull/655
- https://github.com/product-os/jellyfish-plugin-typeform/pull/898

Add relationship validation

---

lib/backend/postgres/index.ts

Previously, the statement and query timeouts were not set and just ran
on the default of 0, which is no timeout. This changes it to 30s.
See https://node-postgres.com/api/client

Set sane statement and query timeouts for postgres

---

lib/backend/postgres/streams.ts

This allows more stream results to be quickly rejected

Streams: Add checking for contract type in `anyOf` expression

---

README.md

The code block is invalid JSON so removing json notation.

Update code block in readme

---

test/integration/kernel.spec.ts

---
`options.mask` should apply additional filter when calling `stream.emit('query', query, { mask })`.

Add test for options.mask when querying dataset

---

lib/cli/generate-contract-interfaces.ts
lib/cli/index.ts
lib/types/contracts/index.ts

Ensure that compiled TypeScript interface definitions are output
in alphabetized order.

Alphabetize interface generation output

---

lib/contracts/transformer-merge-properties.ts

This is part of the effort to align the terminologies with
transformers.
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

Rename `was built into` relationship to `was transformed to`.

---

lib/backend/postgres/streams.ts

This reduces verbosity of stream errors, making them easier to work with.

Don't log entire stream schema on error

---

lib/context.ts
lib/kernel.ts

this fixes:
```log
2022-09-12T23:58:05.476Z [build/index] [crit] [ERROR-SERVER-ID-[205]-PID-16478-IP-48c518345713dcf688106f49426b51b419e3212dc70776033fbd19d36854a3cb-59.9.9]: Unhandled Rejection {}
{
context: { id: 'ERROR-SERVER-ID-[205]-PID-16478-IP-48c518345713dcf688106f49426b51b419e3212dc70776033fbd19d36854a3cb-59.9.9' },
message: 'Unhandled Rejection',
error: TypeError: Cannot read properties of undefined (reading 'properties')
at Stream.<anonymous> (/usr/src/jellyfish/apps/server/node_modules/autumndb/build/kernel.js:1029:62)
}
Process exiting
```
Signed-off-by: Ramiro Gonzalez <ramiro.gonzalez@balena.io>

Avoid throwing on empty properties

---

.github/workflows/flowzone.yml

Temporarily downgrading to older version of flowzone as CI is consistently failing due to problems in more recent version

CI: Use older flowzone tag
