- lib/cards/error.ts
Signed-off-by: Martin Rauscher <martin@balena.io>
> add ui-schema to errors

- lib/index.ts
> Properly export types and modules

- lib/kernel.ts
> Add a `drop` method to the `Kernel` which calls the backend's own `drop`

- lib/kernel.ts
> Expose the backend's `reset` method in the kernel

- lib/kernel.ts
- lib/test-utils.ts
> Add the PG pool to the exported test context

- package.json
> Bump skhema to v6

- README.md
- lib/contracts.spec.ts
- lib/contracts/index.ts
- lib/index.ts
- lib/kernel.ts
- lib/permission-filter.ts
- test/integration/kernel.spec.ts
- test/integration/permission-filter.spec.ts
- test/integration/views.spec.ts
As a preparation of replacing uses of "card" with "contract", alias of core library's public interfaces were created.
> Create alias CARDS -> CONTRACTS

- lib/kernel.ts
- test/integration/kernel.spec.ts
- test/integration/permission-filter.spec.ts
> Fix typo insertConctract -> insertContract

- lib/contracts/index.ts
- lib/kernel.ts
> Typescript provides @deprecated which will be also supported by VSC

- lib/contracts/index.ts
- lib/contracts/role-user-guest.ts
- lib/kernel.ts
> Add role-user-guest

- lib/contracts/index.ts
- lib/contracts/role-user-community.ts
- lib/contracts/role-user-operator.ts
- lib/contracts/role-user-test.ts
- lib/kernel.ts
- test/integration/contracts/role-user-community.spec.ts
---
Bring the following roles into `jellyfish-core`:
- `role-user-community`
- `role-user-operator`
- `role-user-test`
> Bring in more roles

- lib/test-utils.ts
- test/integration/contracts/role-user-community.spec.ts
> Add create user/session test utils and role test

- lib/contracts/mixins/index.ts
> Export uiSchemaDef mixin function

- lib/contracts/mixins/as-pipeline-item.ts
- lib/contracts/mixins/index.ts
- lib/contracts/mixins/with-events.ts
Bring in missing asPipelineItem() and withEvents()
mixin functions from plugin-base
> Add missing mixins

- Dockerfile
- docker-compose.yml
> Bump docker images

- lib/authorization/roles.ts
> Add workaround for `skhema.merge` bug

- lib/authorization/roles.ts
> Add a functioning workaround for `skhema.merge`

- lib/test-utils.ts
- test/integration/kernel.spec.ts
---
- Add marker tests for:
- `kernel.getContractById()`
- `kernel.getContractBySlug()`
- `kernel.query()`
- `kernel.patchContractBySlug()`
- Add `createOrg()` and `createLink()` functions to test utils
- This should allow us to drop `createLink()` from `worker` test utils
> Add marker tests, more test utils

- lib/json-schema.ts
- lib/kernel.ts
- package.json
> Use skhema.SchemaMismatch error

- package.json
> Update skhema from 6.0.5 to 6.0.6

- lib/contracts/mixins/with-events.ts
> Fix mixin events partial function

- package.json
- test/unit/mixins.spec.ts
> Update to major version 6 of Jellyscript

- lib/context.ts
> Log query errors

- lib/contracts/mixins/with-events.ts
> Fix support-thread participants formula

- lib/index.ts
- test/unit/mixins.spec.ts
Dropping this alias in favor of contractMixins
> Drop cardMixins export

- lib/backend/postgres/index.ts
> Last increase of `maxUses`

- lib/contracts/index.ts
- lib/contracts/relationship.ts
- lib/index.ts
- lib/kernel.ts
- lib/test-utils.ts
- lib/types/contracts/relationship.ts
- lib/types/index.ts
> Add relationship type contract

- lib/context.ts
- lib/contracts/index.ts
- lib/contracts/relationship-oauth-provider-has-attached-oauth-client.ts
- lib/contracts/relationship-org-has-member-user.ts
- lib/kernel.ts
- lib/test-utils.ts
- test/integration/kernel.spec.ts
> Add core relationships and kernel cache

- lib/backend/postgres/cards.ts
- lib/backend/postgres/index.ts
- lib/backend/postgres/jsonschema2sql/array-contains-filter.ts
- lib/backend/postgres/jsonschema2sql/sql-filter.ts
- lib/backend/postgres/jsonschema2sql/sql-query.ts
- lib/backend/postgres/links.ts
- lib/backend/postgres/streams.ts
- lib/kernel.ts
- test/integration/kernel.spec.ts
> Alphabetize imports

- lib/kernel.ts
- test/integration/kernel.link.spec.ts
> Temporarily disable relationship error throw

- README.md
> Update code block in readme

- package.json
> Update @types/jest from 28.1.0 to 28.1.1

- lib/kernel.ts
> Enable relationship validation

- lib/contracts/index.ts
- lib/contracts/relationship-user-is-authenticated-with-authentication-oauth.ts
- lib/contracts/relationship-user-is-authenticated-with-authentication-password.ts
- lib/kernel.ts
> Add relationship contracts for authentication contracts

- lib/cli/generate-contract-interfaces.ts
- lib/types/contracts/index.ts
- package.json
> Export contract data interface

- package.json
> Drop jellyfish-jellyscripts dep

- lib/backend/postgres/index.ts
- lib/backend/postgres/streams.ts
- lib/index.ts
- lib/kernel.ts
> Stream options are now of a new, more restricted type `StreamOptions`

- lib/contracts/relationship.ts
> Index commonly queried fields on relationships

- lib/contracts/role-user-community.ts
> Prevent users from viewing other's authentication-password contracts

- lib/backend/postgres/index.ts
> Add migrations table docs

- lib/contracts/user.ts
- lib/types/contracts/user.ts
> Add defaults for user contract

- lib/backend/postgres/index.ts
- lib/context.ts
- test/integration/backend/helpers.ts
- test/integration/backend/index.spec.ts
Patch db options usage.
Signed-off-by: Ramiro Gonzalez <ramiro.gonzalez@balena.io>
> Throw errors.JellyfishDatabaseTimeoutError on all timeouts

- lib/contracts/role-user-operator.ts
> Allow operator role to manage other users

- .github/renovate.json
- .github/workflows/codeql-analysis.yml
- .prettierignore
- .prettierrc
- docker-compose.test.yml
- docker-compose.yml
- package.json
- tsconfig.build.json
- tsconfig.json
- tslint.json
> Dev: Use prettier for json/yml

- .github/renovate.json
> Renovate: Ignore postgres bumps

- docker-compose.yml
- test/integration/backend/postgres/jsonschema2sql/index.spec.ts
> Update to postgres 15

- @types/stopword.d.ts
- lib/kernel.ts
- package.json
> Update stopword, fix typings

- README.md
> Remove old docs action link from readme

- lib/backend/postgres/cards.ts
- lib/backend/postgres/index.ts
- lib/backend/postgres/streams.ts
- lib/cache.ts
- lib/kernel.ts
- package.json
- repo.yml
> Remove jellyfish-metrics

- package.json
> Update fast-equals from 4.0.3 to 5.0.1

- package.json
> Update json-schema-to-typescript to 12.0.0

- lib/backend/postgres/jsonschema2sql/builder-context.ts
> Fix link type string replace

- package.json
> Update json-e from 4.5.1 to 4.5.3

- package.json
> Update semver to 7.5.4

- package.json
> Update @types/semver to 7.5.0
